import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync(new URL('./ToolboxArchiveImport.vue', import.meta.url), 'utf8')

describe('ToolboxArchiveImport', () => {
  it('keeps tags and collections as selector-based inputs instead of JSON or raw ID fields', () => {
    expect(source).toContain('默认标签')
    expect(source).toContain('可选择或输入标签')
    expect(source).toContain('默认视频合集')
    expect(source).toContain('默认图片合集')
    expect(source).toContain('可选，可多选')
    expect(source).not.toContain('JSON 数组')
    expect(source).not.toContain('合集 ID')
  })

  it('keeps the archive file picker bound to an explicit file list before upload', () => {
    expect(source).toContain('v-model:file-list="uploadFiles"')
    expect(source).toContain(':on-change="onUploadChange"')
    expect(source).toContain(':on-remove="onUploadRemove"')
    expect(source).toContain('const uploadFiles = ref([])')
    expect(source).toContain('const input = uploadFiles.value[0]?.raw')
    expect(source).not.toContain('uploadRef.value?.files?.length')
    expect(source).not.toContain('uploadRef.value?.uploadFiles?.length')
  })

  it('supports creating video or image collections in place and filling selectors back', () => {
    expect(source).toContain('createAdminCollection')
    expect(source).toContain('createAdminImageCollection')
    expect(source).toContain('openCreateVideoCollection')
    expect(source).toContain('openCreateImageCollection')
    expect(source).toContain('saveQuickCollection')
    expect(source).toContain('新建视频合集')
    expect(source).toContain('新建图片合集')
    expect(source).toContain('pushSelectedCollectionValue(target, created.id)')
  })

  it('shows localized archive file type and skipped reason in the file list', () => {
    expect(source).toContain('formatArchiveFileType')
    expect(source).toContain('archiveMediaKindLabel')
    expect(source).toContain('formatArchiveReason')
    expect(source).toContain('class="archive-file-item__meta"')
    expect(source).toContain('v-if="file.reason"')
    expect(source).not.toContain('{{ file.media_kind }} · {{ formatFileSize(file.file_size) }}')
  })

  it('lets the archive file list toggle between original order and type sorting', () => {
    expect(source).toContain("const fileSortMode = ref('original')")
    expect(source).toContain('const filteredBatchFiles = computed(() => filterArchiveFilesByGroup(selectedBatchFiles.value, activeGroupFilter.value))')
    expect(source).toContain('const displayedBatchFiles = computed(() => sortArchiveFiles(filteredBatchFiles.value))')
    expect(source).toContain('function sortArchiveFiles(files)')
    expect(source).toContain("'按原始顺序'")
    expect(source).toContain("'按类型排序'")
    expect(source).toContain('<el-segmented v-model="fileSortMode"')
    expect(source).toContain('v-for="file in displayedBatchFiles"')
  })

  it('supports selecting archive files, fast type selection and batch-processing the selected items', () => {
    expect(source).toContain('const selectedFileIDs = ref([])')
    expect(source).toContain('const bulkActions = computed(() => [')
    expect(source).toContain('processSelectionActionLabel')
    expect(source).toContain('function onArchiveFileSelectToggle(row, event)')
    expect(source).toContain('const shouldSelectRange = !isSelected')
    expect(source).toContain('if (shouldSelectRange) {')
    expect(source).toContain('function processSelectedArchiveFiles()')
    expect(source).toContain("selectArchiveFilesByKind('video')")
    expect(source).toContain("selectArchiveFilesByKind('image')")
    expect(source).toContain('BulkActionBar')
    expect(source).toContain('selectedBatchFileCount')
    expect(source).toContain('shiftKey')
    expect(source).toContain(":class=\"{ 'is-selected': selectedFileIDs.includes(String(file.id)) }\"")
    expect(source).toContain('border: 1px solid var(--line-strong);')
    expect(source).toContain('左侧勾选位支持多选和 Shift 连选')
  })

  it('adds a persistent group workspace with ungrouped cards and batch move actions', () => {
    expect(source).toContain('const selectedBatchGroups = ref([])')
    expect(source).toContain("const ARCHIVE_GROUP_FILTER_UNGROUPED = '__ungrouped__'")
    expect(source).toContain('archiveGroupCards')
    expect(source).toContain('未分组固定置顶')
    expect(source).toContain('创建分组')
    expect(source).toContain('加入分组')
    expect(source).toContain('移出分组')
    expect(source).toContain('成员')
    expect(source).toContain('未入库')
    expect(source).toContain('已入库')
    expect(source).toContain("file.group_name || '未分组'")
  })

  it('lets archive video files link to one image collection while images can join image collections', () => {
    expect(source).toContain('selectedVideoImageCollectionID')
    expect(source).toContain('batchEditVideoImageCollectionID')
    expect(source).toContain('仅可关联一个图片图集')
    expect(source).toContain('视频关联的图片合集')
    expect(source).toContain('图片入库后加入的合集')
  })

  it('uses batch title as the default video title and keeps explicit batch title modes available', () => {
    expect(source).toContain('视频默认标题')
    expect(source).toContain('可不填，默认取压缩包文件名')
    expect(source).toContain("title_mode: 'none'")
    expect(source).toContain('batchEditForm.title')
    expect(source).toContain('统一覆盖为同一个标题；留空回到视频默认标题')
    expect(source).not.toContain('title_enabled')
    expect(source).not.toContain('批次标题')
  })

  it('adds filename title drafts without coupling them to process actions', () => {
    expect(source).toContain("{ label: '不修改', value: 'none' }")
    expect(source).toContain("{ label: '统一标题', value: 'uniform' }")
    expect(source).toContain("{ label: '按各自文件名替换', value: 'filename' }")
    expect(source).toContain('DocumentCopy')
    expect(source).toContain('canReplaceArchiveFilenameTitle(selectedFile)')
    expect(source).toContain('applySelectedFilenameTitleDraft')
    expect(source).toContain('使用文件名')
    expect(source).toContain('@input="deactivateSelectedFilenameMode"')
    expect(source).toContain('标题已与文件名一致')
    expect(source).toContain('const persistedFile = findArchiveFileByID(selectedFile.value.id)')
    expect(source).toContain('archiveFilenameEditorMatchesPersistedText(selectedFile.value, persistedFile)')
    expect(source).toContain('标题或说明有未保存修改，请先保存或撤销后再使用文件名')
    expect(source).toContain('buildArchiveFilenameTitleDraft(persistedFile)')
    expect(source).not.toContain('processSelectedArchiveFiles()\n  applySelectedFilenameTitleDraft')
    expect(source).not.toContain('processAdminArchiveImportFile(file.id)\n        applySelectedFilenameTitleDraft')
  })

  it('routes an active single-file filename draft through one semantic request and preserves manual saves', () => {
    expect(source).toContain('const selectedFilenameDraftSnapshot = ref(null)')
    expect(source).toContain('title: String(selectedFile.value.title || \'\')')
    expect(source).toContain('description: String(selectedFile.value.description || \'\')')
    expect(source).toContain('isArchiveFilenameDraftSnapshotCurrent(selectedFilenameDraftSnapshot.value, selectedFile.value)')
    expect(source).toContain('if (selectedFilenameDraftSnapshot.value && !filenameModeActive)')
    expect(source).toContain('if (filenameModeActive)')
    expect(source).toContain('buildArchiveFilenameBatchPayload([selectedFile.value], {')
    expect(source).toContain('update_tags: true')
    expect(source).toContain('update_video_type: true')
    expect(source).toContain('update_video_collection_ids: true')
    expect(source).toContain('update_image_collection_ids: true')
    expect(source).toContain('await batchUpdateAdminArchiveImportFiles(filenamePayload)')
    expect(source).toContain('await updateAdminArchiveImportFile(selectedFile.value.id, payload)')
    expect(source).toContain("error?.data?.reason === 'stale_target'")
    expect(source).toContain("error?.data?.reason === 'ineligible_target'")
  })

  it('uses filename as a mutually exclusive batch title mode with a bounded issue-aware preview', () => {
    expect(source).toContain('<el-segmented')
    expect(source).toContain('v-model="batchEditForm.title_mode"')
    expect(source).toContain('@change="onBatchTitleModeChange"')
    expect(source).toContain("batchEditForm.title_mode === 'filename'")
    expect(source).toContain(':disabled="batchEditForm.title_mode === \'filename\' || !batchEditForm.description_enabled"')
    expect(source).toContain('buildArchiveFilenameBatchPreview(selectedBatchFilesForActions.value, 5)')
    expect(source).toContain('batchFilenamePreview.total')
    expect(source).toContain('batchFilenamePreview.remaining')
    expect(source).toContain('issue.relative_path')
    expect(source).toContain('原标题')
    expect(source).toContain('新标题')
  })

  it('saves filename batches transactionally while leaving uniform mode on the existing loop', () => {
    expect(source).toContain('saveArchiveFilenameBatchUpdate')
    expect(source).toContain("if (batchEditForm.title_mode === 'filename')")
    expect(source).toContain('await batchUpdateAdminArchiveImportFiles(payload)')
    expect(source).toContain('buildArchiveFilenameBatchOptionalPatch({')
    expect(source).toContain('for (const file of targets) {')
    expect(source).toContain("batchEditForm.title_mode === 'uniform'")
    expect(source).toContain('已更新 ${updatedCount} 个视频')
    expect(source).toContain(':disabled="batchEditForm.title_mode === \'filename\' && !batchFilenamePreview.ok"')
  })

  it('keeps dialogs and drafts open when committed updates cannot refresh authority', () => {
    expect(source).toContain('文件信息已保存，但刷新失败，请手动刷新')
    expect(source).toContain('更新已提交，但刷新失败，请手动刷新')
    expect(source.match(/const refreshed = await refreshBatchDetail\(\{ skipConfirm: true \}\)/g)).toHaveLength(4)
    expect(source.match(/if \(!refreshed\) \{/g)).toHaveLength(3)
    expect(source).toContain('const result = await batchUpdateAdminArchiveImportFiles(payload)')
    expect(source).toContain('result?.updated_count')
    expect(source).toContain('Number.isInteger(apiUpdatedCount)')
    expect(source).toContain('已更新 ${updatedCount} 个视频')
  })

  it('keeps the title mode and preview stable in the dense responsive dialog', () => {
    expect(source).toContain('class="archive-title-mode"')
    expect(source).toContain('class="archive-title-preview"')
    expect(source).toContain('class="archive-title-preview__row"')
    expect(source).toContain('class="archive-title-preview__issues"')
    expect(source).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));')
    expect(source).toContain('@media (max-width: 40rem)')
    expect(source).toMatch(/@media \(max-width: 40rem\)[\s\S]*?\.archive-title-preview__row[\s\S]*?grid-template-columns: 1fr;/)
  })

  it('keeps the page batch-first by moving upload into a dialog and batch detail into a drawer', () => {
    expect(source).toContain('uploadDialogVisible')
    expect(source).toContain('batchDrawerVisible')
    expect(source).toContain('title="上传压缩包"')
    expect(source).toContain('title="批次详情"')
    expect(source).toContain('batchEditDialogVisible')
    expect(source).toContain('批量编辑')
    expect(source).toContain('上传成功后会自动打开新批次详情')
  })

  it('moves single-file editing into a row-level dialog without mixing in process actions', () => {
    expect(source).toContain('const selectedFileDialogVisible = ref(false)')
    expect(source).toContain('async function openArchiveFileEditor(row)')
    expect(source).toContain('requestSelectedFileDialogClose')
    expect(source).toContain('handleSelectedFileDialogBeforeClose')
    expect(source).toContain('handleSelectedFileDialogClosed')
    expect(source).toContain('v-model="selectedFileDialogVisible"')
    expect(source).toContain('@click.stop="openArchiveFileEditor(file)"')
    expect(source).toContain('class="archive-file-item__edit"')
    expect(source).toContain('canEditArchiveFile(file)')
    expect(source).toContain('直接点文件行右侧“编辑”')
    expect(source).toContain('处理动作仍走下方主动作区')
    expect(source).toContain('saveSelectedFile')
    expect(source).not.toContain('<SectionCard v-if="shouldShowSingleFileEditor"')
    expect(source).not.toContain('单文件精修')
    expect(source).not.toContain('处理文件</el-button>')
  })

  it('allows deleting archive batches from the batch list with confirmation', () => {
    expect(source).toContain('deleteAdminArchiveImportBatch')
    expect(source).toContain('function canDeleteArchiveBatch(batch)')
    expect(source).toContain('async function removeArchiveBatch(batch)')
    expect(source).toContain("'删除批次'")
    expect(source).toContain('删除后会清空该批次的压缩包记录、文件清单和解包目录')
    expect(source).toContain('archive-batch-card__actions')
  })
})
